services:
  - type: web
    name: izumi-md
    repo: https://github.com/Akshay-Eypz/izumi
    branch: main
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: SESSION_ID
        sync: false
        required: true
      - key: PREFIX
        sync: false
      - key: SUDO
        sync: false
        require: true
      - key: MODE
        value: "private"
        sync: true
        require: true
      - key: LOG_MSG
        value: "false"
        sync: true
        require: false
      - key: READ_MSG
        value: "false"
        sync: true
        require: false
      - key: PORT
        value: "3000"
        sync: true
        require: false
